name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build-ubuntu-latest:
    
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
          cat /proc/cpuinfo
          echo "file_created $(date)" > ${GITHUB_SHA}-ubuntu.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: build_artifact
          path: ${GITHUB_SHA}-ubuntu.txt

  build-ubuntu-latest2:
    
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
          cat /proc/cpuinfo
          echo "file_created2 $(date)" > ${GITHUB_SHA}-ubuntu2.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: build_artifact
          path: ${GITHUB_SHA}-ubuntu2.txt

  build-complete:

    runs-on: ubuntu-latest
    needs: [build-ubuntu-latest]

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'pull_request' }}
    steps:
      - name: complete?
        run: |
          echo "complete $(date)" > ${GITHUB_SHA}-complete.txt

      - name: Completion
        uses: actions/upload-artifact@v3
        with:
          name: build_artifact
          path: ${GITHUB_SHA}-complete.txt
