name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-docker-release:
    
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Git-clone
        run: |
          git submodule update --init --recursive

      - name: Compile
        run: |
          bash script.sh
