name: Releaase

on:
  workflow_run:
    workflows: [Build]
    branches: [main]
    types: [completed]

jobs:
  build-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: build_artifact
          path: ${GITHUB_SHA}-*.txt
    
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.txt
